### ISSUE TITLE
BP3L Disconnection

### ISSUE THREAD

**Issue by fjsosa** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#1]
Hi, I'm Fernando Sosa, I work for On3Health, we use your SDK to connect to BG1, BP5 and BP3L and more devices in the future, I having a problem disconnecting BP3L, After use the device I'm closing the BT Connection, but the devices keeps connected to the app (the light in the device is on), if I kill my app the device is disconnected, I'm also setting the objects implicated in the connection to nil, (manager and device objects). If you can give me some clues about this issue it will be great! thenk ayou (using 1.0.15 for IOS) thank you!

**Comment by jzhw0130** [comment]
Sorry for late reply.  The problem has been fixed .
