### ISSUE TITLE
enum HealthDeviceType add  HealthDeviceType_BP7 support

### ISSUE THREAD

**Issue by futomtom** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#10]
there is not HealthDeviceType_BP7 in  enum HealthDeviceType. should it use BP7S instead? or BP7 should NOT use enum value BP7S
I have a BP7, I want to connect it and measure. Thank you.

**Comment by futomtom** [comment]
does it mean BP7 can connect directly without need to be discovered.  from the Doc/  一開始就連接了

**Comment by qqskim** [comment]
Sure

For iHealth device  with bluetooth low energy , you have to discover, then connect.

But for iHealth device with bluetooth 3.0, there is no need to discover, because you need to connect iHealth device with your phone  on the bluetooth page (Setting page)

**Comment by futomtom** [comment]
I have a BP7.  is BP7 BLE device or 3.0 device?  From the example code. BP7 is a BLE device.  there is no BP7 in HealthDeviceType, how to  set  ScanDeviceController:commandScanDeviceType to scan BP7, thank you

**Comment by jzhw0130** [comment]
@futomtom 

Sure  

BP7 is Bluetooth 3.0, no need to scan.

Only need to register the notification:

[[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(DeviceConnectForBP7:) name:BP7ConnectNoti object:nil];
[[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(DeviceDisConnectForBP7:) name:BP7DisConnectNoti object:nil];
[BP7Controller shareBP7Controller];
