### ISSUE TITLE
UserAuthen_UserInvalidateRight

### ISSUE THREAD

**Issue by Zestu** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#11]
I use SDK in an app where user has no option to login with his iHealth account, app itself manages user's data storage.
With one of device types, glucometer BG5, I receive error UserAuthen_UserInvalidateRight, sometimes it disappears.
In documents it's described as "User hasn't been authorized", but what does it mean ??

**Comment by qqskim** [comment]
Hi

It means your clientID clientSecret or userID is invalid.

Could you send your demo code?

Jing

**Comment by Zestu** [comment]
Actually I'm replacing credentials in iHealthSDKDemo and they work for weight scale and BP

**Comment by Zestu** [comment]
I can send you account name via email, could you check is it eligible to work with BG API ?

**Comment by qqskim** [comment]
ok

Email:  jingzhiwei@ihealthlabs.com.cn <mailto:jingzhiwei@ihealthlabs.com.cn>

**Comment by Zestu** [comment]
Good, it works, thank you for your help
