### ISSUE TITLE
App Would Like to Access the Microphone

### ISSUE THREAD

**Issue by shorbenko** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#12]
Application with integrated iHealthSDK request access to my microphone when I plug in a headset with a mic. 
I would like to get rid of this pop-up window. Is it safe to skip initialization of BG audio module if I support only bg5 glucometer model:
` [[BG1Controller shareBG1Controller]initBGAudioModule];`
Will it solve my problem?

**Comment by qqskim** [comment]
Sure

It is ok.
