### ISSUE TITLE
How to Scan BP5 device

### ISSUE THREAD

**Issue by saadhasaan** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#15]
Hi, 
In example code I am unable to find the code for scanning BP5 device. And also in enum HealthDeviceType, there is no value for that device. Can someone guide me regarding that.

Thanks

**Comment by jzhw0130** [comment]
@saadhasaan 
Hi,

Because BP5 work with bluetooth 3.0, you have to connect it on bluetooth page on setting.
So no need to call scan, only register the connect notification and wait is ok.

Jing
