### ISSUE TITLE
How to disconnect and do not connect BG5 device to iPhone?

### ISSUE THREAD

**Issue by shorbenko** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#16]
In the iHealthSDK version 2.0.5, I don't see any method in BG5.h or BG5Controller.h to disconnect the BG5 device and then do not connect to iPhone so that user could make the "offline" measurement.

**Comment by wushuang2012** [comment]
@shorbenko BP5 is common bluetooth products, not through the instruction disconnect, you can turn off the phone bluetooth BP5 offline measurement
