### ISSUE TITLE
Help required for HS6 device connect cycle

### ISSUE THREAD

**Issue by saadhasaan** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#17]
Hi,

I am new to these devices, so that asking that beginner question. I want to integrate HS6 device, but don't know the connect/fetch data cycle for that device as its wireless connect device. Can someone help me regarding that. I want to know the steps I should follow for that device.

Thanks

**Comment by wushuang2012** [comment]
@saadhasaan HS6 data uploaded to the server, you can according to we provide interfaces to pull data
