### ISSUE TITLE
UserAuthenResult:5

### ISSUE THREAD

**Issue by hovkaren** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#18]
When I connect to a device from your example(I am using device HS4) always getting UserAuthenResult=5 error. My clientID is 19a675c6cea0430593774b14fc272eda.

**Comment by wushuang2012** [comment]
@hovkaren you can check  the HealthUser ：clientSDKID、clientSDKSecret、clientSDKUserName.   clientSDKUserName must be an email .

**Comment by hovkaren** [comment]
I have set HealthUser : clientID = 19a675c6cea0430593774b14fc272eda, clientSecret = ******************* and userID = thenshah@gmail.com  with documentation but same error UserAuthenResult=5.

**Comment by wushuang2012** [comment]
@hovkaren Your account has not yet passed the certification of ihealth website
