### ISSUE TITLE
HS4 Device Not Connect or Discover (Notification method not receive Descover method)

### ISSUE THREAD

**Issue by sw-tt-hardikgajjar** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#22]
Hi, 
i am not able to Receive Notification method for HS4 Scale Connectin

-(void)DeviceDiscoverForHS4:(NSNotification *)tempNoti method not called even device start 

i test on Old version SDK 
iHealthSDK2.0 where i able to recieve DeviceDiscoverForHS4 notification but with this new SDK and Demo i am not able to get device information with connetcion , can you please suggest me?

**Comment by sw-tt-hardikgajjar** [comment]
Hi IHealthLab, 
@wushuang2012 
@iHealthLabs 

We are not able to connect the HS4 Scale Device with this iHealthSDK2.0, SDK not responsding for their DeviceDiscoverForHS4 Notification method, or Connect Method for same. 
can you please suggest us as soon as possible?

Thanks

**Comment by wushuang2012** [comment]
@sw-tt-hardikgajjar You should go to call the method to scan HS4  ：-(int)commandScanDeviceType:(HealthDeviceType)tempDeviceType     and Must ensure that HS4 is activated
