### ISSUE TITLE
Where did the library go? :D 

### ISSUE THREAD

**Issue by rimonhanna** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#23]

**Comment by NarenLK** [comment]
Did you get the library?

**Comment by rimonhanna** [comment]
Yes, but now we need to request each new version rather than checking the github repo for updates. I understand the need for you to make it private but we need a better centralised way for us to download the library each time there is an update.

**Comment by NarenLK** [comment]
How about the users who are already having the previous library ? is it still valid ?

**Comment by jialiabc** [comment]
@NarenLK 

Yes, they still need to apply, they need to contact:

a. yuchen.wang@ihealthlabs.com(US)
b. noah@ihealthlabs.com(Europe)
