### ISSUE TITLE
HS5: HS5Controller Object is shown a blank array of HS5 Instance.

### ISSUE THREAD

**Issue by piyushbm** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#25]
Hi,
I have received notifications of "HS5ConnectNoti" and "HS5DisConnectNoti", but when I am trying to fetch **HS5 Instance** from HS5Controller then I am getting a blank array of HS5.

HS5Controller *hsController = [HS5Controller shareIHHs5Controller];
NSArray *hsArray = [hsController getAllCurrentHS5Instace];
Shown **0 count** of hsArray

iHealthSDK version is 2.0

**Comment by wushuang2012** [comment]
@piyushbm Only when the HS5 connection is successful is the array numeric

**Comment by piyushbm** [comment]
@wushuang2012 Thanks for your reply.
 Connection already established, I already got notification of "HS5ConnectNoti".
 In notification method I am going to fetch array, but its showing 0 count.

**Comment by wushuang2012** [comment]
@piyushbm 
You could write code like this

 [[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(DeviceConnectForHS5:) name:HS5ConnectNoti object:nil];

-(void)DeviceConnectForHS5:(NSNotification *)tempNoti{
    
    HS5Controller *hsController = [HS5Controller shareIHHs5Controller];
    NSArray *hsArray = [hsController getAllCurrentHS5Instace];
    
    if(hsArray.count>0){
       
       ..............
    }

    
    
}

**Comment by piyushbm** [comment]
-(void)DeviceConnectForHS5:(NSNotification *)tempNoti{

HS5Controller *hsController = [HS5Controller shareIHHs5Controller];
NSArray *hsArray = [hsController getAllCurrentHS5Instace];

if(hsArray.count>0){
  
} else {
  // Notification method called but its run comes to else condition.
}
}

Notification method called but everytime its comes to else condition because hsArray.count is 0.

Above code and device were worked fine on SDK 1.0.7 but in SDK 2.0 its facing issues.

**Comment by wushuang2012** [comment]
@piyushbm 
You can update to the latest SDK
a. yuchen.wang@ihealthlabs.com(US)
b. noah@ihealthlabs.com(Europe)

**Comment by piyushbm** [comment]
Thanks for update.
I have sent a mail please share me latest SDK.

**Comment by piyushbm** [comment]
Hey,
Please share a latest SDK.

**Comment by jialiabc** [comment]
@piyushbm 
Please send me sdk@ihealthlabs.com.cn an e-mail with your personal email, your region, and I will reply to you about what to do next.

**Comment by piyushbm** [comment]
Hey Team,
 I have sent few mails to sdk@ihealthlabs.com.cn but I didn't get any reply or latest SDK.
 Can you please help me. Its very urgent.

**Comment by jialiabc** [comment]
share the latest sdk  on 11.13

**Comment by piyushbm** [comment]
Thanks for sharing latest SDK.
