### ISSUE TITLE
Link to the Examples is broken. 

### ISSUE THREAD

**Issue by NarenLK** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#26]

**Comment by jialiabc** [comment]
@NarenLK
Contact for more information:
a. yuchen.wang@ihealthlabs.com(US)
b. noah@ihealthlabs.com(Europe)

**Comment by NarenLK** [comment]
@jialiabc How about the users who are already having the library ? is it still valid ?

**Comment by jialiabc** [comment]
@NarenLK

Yes, they still need to apply, they need to contact:

a. yuchen.wang@ihealthlabs.com(US)
b. noah@ihealthlabs.com(Europe)
