### ISSUE TITLE
Lib doesn't support architecture x86_64 (Simulator) 

### ISSUE THREAD

**Issue by terrettazmaxime** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#3]
lipo -info iHealthLibrary(2.0.4).a
Architectures in the fat file: iHealthLibrary(2.0.4).a are: armv7 arm64

**Comment by MariusMez** [comment]
Same problem here : https://github.com/iHealthLabs/IOS-SDK/issues/5

**Comment by jzhw0130** [comment]
@terrettazmaxime @MariusMez 
Sure, the architectures contains : armv7  arm64, not support x86_64.
Because we use a third library, the library does not support x86_64. 
Sorry.
