### ISSUE TITLE
Multiple measures with the same ID on SP02

### ISSUE THREAD

**Issue by fchenebault** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#4]
Since the SDK v1.0.16, every measure got a dataID, to be able to identify a measure.
But sometimes, the same dataID is send multiple times, with measure different values.
This append if we take multiple measure without turning down the SPO2 between measures (even using the disconnection SDK method).

Here is an example, taking 2 consecutive measures without turning the SPO2 down :

```
Measure 1

{
PI = "1.628159";
bpm = 69;
dataID = 02b7a00fccbda24355b3dbb52cb9232e;
height = 0;
spo2 = 98;
wave = (166, 132, 95);
}

Measure 2

{
PI = "1.635432";
bpm = 69;
dataID = 02b7a00fccbda24355b3dbb52cb9232e;
height = 6;
spo2 = 98;
wave =     (15, 220, 339);
}
```

Thanks for your help.

**Comment by wushuang2012** [comment]
@fchenebault We will solve the problem in a new version of the SDK

**Comment by fchenebault** [comment]
Nice ! Do you now when this new version will be available ? 
Is there is changelog somewhere ?

Thanks

**Comment by wushuang2012** [comment]
@fchenebault   We will solve the problem, as soon as possible after the completion of the test is to update the SDK, we will explain each version of the SDK update content, I'm very sorry to inconvenience you
