### ISSUE TITLE
Problem with BP3L Device List

### ISSUE THREAD

**Issue by fjsosa** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#5]
Hi, I'm Working with a BP3L device and I'm having problem to get the list fo Connected Devices (BP3LController getAllCurrentBP3LInstance), my steps are:

1) wait for the event BP3LDiscover
2) check the serial number
3) connect the device (ConnectDeviceController commandGetInstance commandConectWithDeviceType), (returns 0)
4) get device instance (BP3LController getAllCurrentBP3LInstance): the device list returned is empty.

Should I wait a given time until this list get updated? 
Is this the correct behavior, or it is a bug? I can do a do-while loop until this list get updated but it seems more a workaround than a real fix.

thank you so much for your help.

Fernando Sosa.

**Comment by jzhw0130** [comment]
@fjsosa 
1) wait for the event BP3LDiscover
2) check the serial number
3) register notification:
[[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(DeviceConnectForBP3L:) name:BP3LConnectNoti object:nil];
4) connect the device (ConnectDeviceController commandGetInstance commandConectWithDeviceType),
5) get device instance (BP3LController getAllCurrentBP3LInstance)， after receive the notification.
-(void)DeviceConnectForBP3L:(NSNotification *)tempNoti{
    BP3LController *controller = [BP3LController shareBP3LController];
    NSArray *bpDeviceArray = [controller getAllCurrentBP3LInstace];
}
