### ISSUE TITLE
Bluetooth GATT Support

### ISSUE THREAD

**Issue by eburns1148** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#8]
Does any of your health devices conform to the standard Bluetooth GATT specification, for Blood Pressure, ect..

https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.blood_pressure.xml

I would like to be able to read blood pressure data directly from the iHealth device, is this possible without use of this SDK?

**Comment by qqskim** [comment]
We have a type of blood pressure monitor with Continua protocol(BLE) , but only made for special customer.

For other type of iHealth devices , need to read data for iHealth SDK.

**Comment by DanilBorchevkin** [comment]
@qqskim I have some question.

Why vendors of the mobile health products (blood pressure monitors for example) design proprietary protocols (iHeath Track, Omron M7 for example) instead using adopted GATT services and characteristics? What reason of it?

**Comment by jzhw0130** [comment]
Hmm..

1. With proprietary  protocol, we can do more functions which is not supported by GATT services.
2. Comercial reason..

**Comment by DanilBorchevkin** [comment]
@jzhw0130 It is clearly and doesn't invoke any questions 👍 

This is not related to the requirements of the FDA?

**Comment by qqskim** [comment]
Not required by FDA
