### ISSUE TITLE
Automation testing of iOS iHealthSDK

### ISSUE THREAD

**Issue by shorbenko** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#9]
1. How do you perform regression testing of new releases of iHealthSDK for all devices and platforms?
2. Does iOS iHealthSDK have unit or integration tests which can be shared?
3. Can you advise any technics to mock calls to iHealth devices at Bluetooth level so I can write automation tests by myself for your SDK?  As an example there is a  tool that provides in-app device simulation https://github.com/Raizlabs/RZBluetooth

**Comment by wushuang2012** [comment]
@shorbenko We have tested the SDK professional testers, because a lot of test content, there may be the place where we test does not reach the designated position, we will improve in the later work, we temporarily haven't relevant test documents can be provided
